#!/bin/sh
# Rebuild src/app/icon.svg from tools/logo-source.jpg.
#
# The icon is the studio's mark vectorised, not redrawn, so the artwork of record
# is the JPEG next to this script and the SVG is output. This script exists so
# that stays true: if the mark is ever revised, replace the JPEG and run this,
# rather than editing the path in the SVG, which is machine output and is not
# editable in any meaningful sense.
#
#   brew install potrace     # supplies both potrace and mkbitmap
#   sh tools/trace-icon.sh
#
# The blur is the setting worth understanding. The mark occupies only about 124px
# of the source JPEG, and tracing that crop unblurred follows every compression
# artefact along the edges: 7800 characters of path. At -b 1.2 the same shape
# comes out in 2155, and rendered side by side at 300px the two cannot be told
# apart. The difference was compression noise, not logo. Raise the blur much
# further and the corners of the square begin to round off.
#
# CROP is measured, not guessed: the dark pixels of the source span x 228..351
# and y 133..253, whose centre is also the centre of the image, which is why a
# centred square crop lands on the mark. A differently framed source needs that
# remeasured; everything after it adapts on its own.
set -e

cd "$(dirname "$0")/.."
SRC=tools/logo-source.jpg
OUT=src/app/icon.svg
CROP=132      # square crop around the mark, with a few px of margin
SCALE=8       # upsample before threshold, so the traced curves have resolution
FILL=464      # how much of the 512 viewBox the mark should occupy

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

sips -s format bmp "$SRC" --out "$WORK/src.bmp" >/dev/null
sips -c $CROP $CROP "$WORK/src.bmp" --out "$WORK/crop.bmp" >/dev/null
mkbitmap -x -s $SCALE -b 1.2 -t 0.5 "$WORK/crop.bmp" -o "$WORK/big.pbm"
potrace -s -u 10 -a 1.2 -O 0.6 --flat "$WORK/big.pbm" -o "$WORK/traced.svg"

python3 - "$WORK/traced.svg" "$WORK/big.pbm" "$OUT" $FILL <<'PY'
import re, sys

traced, pbm, out, fill = sys.argv[1], sys.argv[2], sys.argv[3], float(sys.argv[4])
CANVAS = 512.0

# Where the mark actually sits, read off the bitmap potrace was given rather than
# off the path it produced. The path is a mix of absolute and relative commands
# in potrace's own units, and guessing its extent from the numbers in it is how
# you end up with a mark that is centred by luck. The bitmap is unambiguous, and
# potrace's own transform maps it back to exactly these pixel coordinates, so the
# bbox measured here is the bbox in the coordinate space the wrapper works in.
data = open(pbm, 'rb').read()
fields = []
while len(fields) < 3:      # exactly three: magic, width, height, and no further
    m = re.match(rb'\s*(?:#[^\n]*\n)?(\S+)', data)
    fields.append(m.group(1)); data = data[m.end():]
assert fields[0] == b'P4', f'expected a binary PBM, got {fields[0]!r}'
w, h = int(fields[1]), int(fields[2])
bits = data[1:]             # a single whitespace byte, and then raw pixels
row_bytes = (w + 7) // 8
assert len(bits) == row_bytes * h, f'header and pixel data disagree: {len(bits)} bytes for {row_bytes * h}'

x0, y0, x1, y1 = w, h, -1, -1
for y in range(h):
    row = bits[y * row_bytes:(y + 1) * row_bytes]
    if not any(row):                        # PBM: a 1 bit is black
        continue
    y0 = min(y0, y); y1 = max(y1, y)
    for x in range(w):
        if row[x >> 3] >> (7 - (x & 7)) & 1:
            if x < x0: x0 = x
            if x > x1: x1 = x
pw, ph = x1 - x0 + 1, y1 - y0 + 1

# One scale factor for both axes: the mark is genuinely a little wider than it is
# tall, and squaring it up would stretch the artwork. The slack goes into the
# vertical margin.
k = fill / pw
tx = (CANVAS - fill) / 2 - k * x0
ty = (CANVAS - ph * k) / 2 - k * y0

inner = re.search(r'(<g transform=.*?</g>)', open(traced).read(), re.S).group(1)
inner = re.sub(r'\s*fill="#000000"', ' fill="#000"', inner)
inner = '\n'.join('    ' + ln.strip() for ln in inner.strip().splitlines())

open(out, 'w').write(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Nguyễn Ngọc Nam Anh">
  <!--
    Generated by tools/trace-icon.sh from tools/logo-source.jpg. Do not edit: the
    path is traced output, and the transforms are derived from where the mark
    landed in the bitmap. Change the artwork or the framing and re-run the script.

    Next.js serves this from its filename alone; the rules are in
    node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/01-metadata/app-icons.md

    The white ground is deliberate, not padding. The artwork is pure black and a
    tab strip in a dark theme would swallow it if this were transparent.
  -->
  <rect width="512" height="512" fill="#fff"/>
  <g transform="translate({tx:.3f} {ty:.3f}) scale({k:.7f})">
{inner}
  </g>
</svg>
''')

print(f'mark {pw}x{ph} at ({x0}, {y0}) in a {w}x{h} bitmap')
print(f'wrote {out}')
PY
